export class SplashBean {
  createAt:        Date;
  modifyAt:        Date;
  organizationUid: string;
  id:              number;
  location:        string;
  title:           string;
  pictureUrl:      string;
  hrefUrl:         string;
  hrefTargetType:  string;
  seq:             number;
  active:          boolean;
  publishDt:       Date;
  createUserId:    number;
  createUname:     string;
}

